### ISSUE TITLE
Compilation failed on Windows

### ISSUE THREAD

**Issue by alick888** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#33]
When I do a mvn clean install on this version on Windows, there is an error complaining "command line too long".   The workaround is to remove the maven-jdeps-plugin and jacoco-maven-plugin from the pom.xml before I can compile on Windows.  Attached please find the error in more details.  

 
[command line too long.txt](https://github.com/user-attachments/files/16686261/command.line.too.long.txt)

**Comment by amirkhan-ak-sf** [comment]
@alick888 thanks for submitting the issue. Can you please check what your local mvn path looks like? 
This pretty much sounds like a windows issue where the path in the command is too long. 

@arpitg-1 @dipeshkumardutta-sfemu any idea?

**Comment by dipeshkumardutta-sfemu** [comment]
In windows there is [limitation](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation) in Command Prompt, the total length of the command line can't contain more than 8191 characters. But the attached command length is 21104.
As of now if removing jdeps plugin works fine then continue with that until we are not coming up with a solution. Also you can try with cygwin in windows.

**Comment by Nandinireddy0027** [comment]
Hi Team,

I removed jdeps plugin  after that I got these error Failed to execute goal com.mulesoft.munit:munit-extensions-maven-plugin:1.2.0:test (default-test) on project mulechain-ai-connector: There was an error running MUnit tests


![image](https://github.com/user-attachments/assets/512b67c7-6a37-4985-ba1c-fbdb1734f93f)
