### ISSUE TITLE
Image Read Operation Throwing error

### ISSUE THREAD

**Issue by CC-isha** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#44]
I have been trring to read an Image through Open AI. Currentlu Operating on Windows Machine. I am passing the data and image url. However the connector seems to throw error. 
<img width="860" alt="error" src="https://github.com/user-attachments/assets/f0f0cc84-694d-472d-9a7e-fe4888a322a0">

**Comment by amirkhan-ak-sf** [comment]
Hi @CC-isha 

can you take a snapshot of the operation details? 

In my mule app I have configured the operation like this: 
<img width="945" alt="image" src="https://github.com/user-attachments/assets/143082ac-a278-4851-8a3a-657de800c237">

And call it with this request: 
<img width="1127" alt="image" src="https://github.com/user-attachments/assets/22ba695c-83ba-496e-8e1c-2a3b728d7e41">

And you see it describes the image. 

Let me know. Thanks!

**Comment by CC-isha** [comment]
Hi @amirkhan-ak-sf, 
Thank you for your assistance. I realized that I had overlooked specifying the correct model in this case.

Thank you!
