### ISSUE TITLE
error during mvn clean install -Dmaven.test.skip=true -DskipTests

### ISSUE THREAD

**Issue by ettoregia** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#48]
When running `mvn clean install -Dmaven.test.skip=true -DskipTests` I get the error reported below which, by looking at the other issue on `mvn formatter:format` I tried to resolve by first running `mvn formatter:format` but it returned a further error still reported below. 

I'll investigate it further

### Discussed in https://github.com/orgs/MuleSoft-AI-Chain-Project/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **alick888** August 21, 2024</sup>
If you see a formatter error when you try to run mvn on a MAC project (usually only happens on the first time), you can run the following command first before rerunning mvn install again:

                mvn formatter:format

After seeing "BUILD SUCCESS", you can proceed to rerun your mvn command</div>

[mvn clean install -Dmaven.test.skip=true -DskipTests.txt](https://github.com/user-attachments/files/16847936/mvn.clean.install.-Dmaven.test.skip.true.-DskipTests.txt)
[mvn-formatter-erro.txt](https://github.com/user-attachments/files/16847940/mvn-formatter-erro.txt)

**Comment by amirkhan-ak-sf** [comment]
@dipeshkumardutta-sfemu @arpitg-1 Any idea on this one?

**Comment by alick888** [comment]
Hi @ettoregia, which repository are you trying to compile?  Are you using MAC or Windows?  I'll try to see if I can reproduce the issues and how it can be resolved.

**Comment by amirkhan-ak-sf** [comment]
@alick888 its Macbook Pro. 

@ettoregia as a reference as already shared here the link: https://stackoverflow.com/questions/67833372/getting-blocked-mirror-for-repositories-maven-error-even-after-adding-mirrors - maybe disabling mirrors temporarily solve the issue.

**Comment by ettoregia** [comment]
Hi all, it is on MAC. By following the guide linked by @amirkhan-ak-sf eventually worked. I wonder why it didn't happen to others.

**Comment by ettoregia** [comment]
Closed
