### ISSUE TITLE
Classloading conflict when changing OpenAI model

### ISSUE THREAD

**Issue by jdollenbacher** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#51]
When changing the model, e.g. chatGPT4 to chatGPT3.5 or vice versa, in Anypoint Studio during development, hotdeployment fails with 
`org.mule.runtime.module.deployment.impl.internal.application.DefaultMuleApplication: java.lang.UnsatisfiedLinkError: Native Library /Users/username/.djl.ai/tokenizers/0.15.0-0.26.0-osx-x86_64/libtokenizers.dylib already loaded in another classloader`
A full restart of the app is required.

**Comment by amirkhan-ak-sf** [comment]
Hi @jdollenbacher 

that is a known issue. This is do to the way we've loaded the classes. Currently, we have to live with this limitation.
