### ISSUE TITLE
Connect to openai.azure.com

### ISSUE THREAD

**Issue by EmmanuelAnudeep** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#55]
For one of our use case connecting to azure cognitive search, I am not able to connect to azure with provided option OPENAI in vector config as embedding provider type and vector db provider type. Is it something I am missing to configure?  could you please help me here.

**Comment by amirkhan-ak-sf** [comment]
Azure Search is not supported by the Vectors connector as of today. We have it on our Roadmap for November .

**Comment by EmmanuelAnudeep** [comment]
Thanks Amir :)
