### ISSUE TITLE
Methods not returning proper JSON documents

### ISSUE THREAD

**Issue by jdollenbacher** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#57]
The methods
- Sentiment analyze
- RAG load document
do not return a proper JSON documents but a JSON-formatted string (mediaType = */*), which requires an additional transformation in Dataweave ( read(payload, "application/json") ) for further processing. Returning document type "application/json" would be more convenient and straight forward.

**Comment by amirkhan-ak-sf** [comment]
Please download the latest connector Version from the master Branch 0.3.0 which has been release on 1st of September. You don't have to do the conversion anymore.
