### ISSUE TITLE
After removing jdeps plugin

### ISSUE THREAD

**Issue by Nandinireddy0027** [MuleSoft-AI-Chain-Project/mulesoft-ai-chain-connector#60]
Hi Team,

I removed jdeps plugin after that I got these error Failed to execute goal com.mulesoft.munit:munit-extensions-maven-plugin:1.2.0:test (default-test) on project mulechain-ai-connector: There was an error running MUnit tests
![Screenshot 2024-09-23 130754](https://github.com/user-attachments/assets/6e47c618-a3e1-457d-824a-6824273dbcea)

**Comment by amirkhan-ak-sf** [comment]
Can you please run  `mvn clean install -Dmaven.test.skip=true -DskipTests`

**Comment by Nandinireddy0027** [comment]
Hi Amir Khan,
Thank you for your response 
I got Build Success
![image](https://github.com/user-attachments/assets/5d3e3c16-789c-4647-91f6-cd59abeb8d69)
